### PR TITLE
add product prices to modal view

### PR DESCRIPTION
**Pull request by michelesr**
add feature requested in #8

### CODE REVIEW

**Comment by espositocloud** [comment]
Why making a custom filter insted of the [built-in one](https://docs.angularjs.org/api/ng/filter/currency)?

**Comment by michelesr** [comment]
cuz decimal part is separated with comma instead of point and:
`return parseFloat(value.replace(',','.')).toFixed(2).toString() + " " + currencySymbol;`
replaces `,` with `.` before converting to fixed point decimal

**Comment by espositocloud** [comment]
WTF?!?  @matteo88 does the GDXP expect an Italian-specific numeric standard?!

**Comment by michelesr** [comment]
Reverted because hide/show price should be a flag in the code, and not a UI
feature.

**Comment by michelesr** [comment]
Implemented flag

**Comment by warp10** [comment]
Looks good, approved

**Pull request merged**
